#!/usr/bin/env bash

set -e

. "./utils/bitwarden"
. "./utils/cleanup"
. "./utils/install"
. "./utils/log"

install fzf

modules="$(find ./modules -type f | fzf --prompt "Select modules: " --multi --layout=reverse --height=20)"

log "Selected modules:"
for module in $modules; do
  log "  $module"
done

for module in $modules; do
  log "Running module '$module'..."
  . "$module"
done
