#!/usr/bin/env bash

function bw_unlock() {
  set +e
  while [[ -f "/usr/local/bin/bw" ]] && [[ -z "$BW_SESSION" ]]; do
    BW_SESSION="$(bw unlock --raw)"
  done
  set -e
}

function bw_lock() {
  [[ -f "/usr/local/bin/bw" ]] && bw lock
}
