#!/usr/bin/env bash

log "Installing keyring..."
sudo rm -f /etc/apt/keyrings/docker.gpg
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
log "Installing sources list..."
sudo rm -rf /etc/apt/sources.list.d/docker.list
cat <<EOF | sudo tee /etc/apt/sources.list.d/docker.list
deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$UBUNTU_CODENAME") stable
EOF
sudo apt update
log "Installing..."
install "docker-ce"
log "Add user to to docker group..."
sudo usermod -aG docker $(whoami)
